// src/contexts/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  ar: {
    totalSales: 'إجمالي المبيعات',
    totalOrders: 'عدد الطلبات',
    totalProducts: 'عدد المنتجات',
    totalCustomers: 'عدد العملاء',
    home: 'الرئيسية',
    cart: 'السلة',
    tracking: 'تتبع الطلب',
    notifications: 'الإشعارات',
    admin: 'لوحة التحكم',
    search: 'البحث برقم التتبع',
    welcomeTitle: 'مرحباً بكم في Dream Boutique',
    welcomeSubtitle: 'اكتشفوا أفضل البراندات العالمية في مكان واحد',
    ourBrands: 'برانداتنا',
    featuredProducts: 'منتجات مميزة',
    viewProducts: 'عرض المنتجات',
    visitInstagram: 'زيارة الإنستغرام',
    addToCart: 'إضافة للسلة',
    classicColorShop: 'Classic Color Shop',
    ghyma68: 'Ghyma68',
    designerrMix: 'Designerr Mix',
    products: 'المنتجات',
    price: 'السعر',
    jod: 'دينار أردني',
    inStock: 'متوفر',
    outOfStock: 'غير متوفر',
    dashboard: 'لوحة التحكم',
    productManagement: 'إدارة المنتجات',
    orderManagement: 'إدارة الطلبات',
    featuredManagement: 'المنتجات المميزة',
    discountManagement: 'إدارة الخصومات',
    userManagement: 'الموظفين والصلاحيات',
    reportsAndSales: 'التقارير والمبيعات',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل منتج',
    deleteProduct: 'حذف منتج',
    productName: 'اسم المنتج',
    productPrice: 'السعر',
    productBrand: 'البراند',
    productImage: 'صورة المنتج',
    color: 'اللون',
    size: 'المقاس',
    quantity: 'الكمية',
    uploadImage: 'رفع صورة المنتج',
    save: 'حفظ',
    cancel: 'إلغاء',
    orders: 'الطلبات',
    addOrder: 'إضافة طلب',
    editOrder: 'تعديل طلب',
    deleteOrder: 'حذف طلب',
    orderNumber: 'رقم الطلب',
    customerName: 'اسم العميل',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    model: 'الموديل',
    notes: 'ملاحظات',
    status: 'الحالة',
    trackingNumber: 'رقم التتبع',
    pending: 'قيد التنفيذ',
    shipped: 'جاري الشحن',
    delivered: 'تم التسليم',
    returned: 'مرتجع',
    cancelled: 'ملغي من العميل',
    contact: 'تواصل معنا',
    complaints: 'الشكاوي والتواصل',
    email: 'البريد الإلكتروني',
    featureNotImplemented: '🚧 هذه الميزة غير مطبقة بعد',
    featureNotImplementedDesc: 'لا تقلق! يمكنك طلبها في رسالتك التالية! 🚀',
    productAdded: 'تم إضافة المنتج بنجاح',
    productUpdated: 'تم تحديث المنتج بنجاح',
    productDeleted: 'تم حذف المنتج بنجاح',
    orderAdded: 'تم إضافة الطلب بنجاح',
    orderUpdated: 'تم تحديث الطلب بنجاح',
    orderDeleted: 'تم حذف الطلب بنجاح',
    lightTheme: 'فاتح',
    darkTheme: 'غامق',
    aboutUs: 'تعرف علينا',
    ourStory: 'قصتنا',
    termsAndConditions: 'الشروط والأحكام',
    subscribeNewsletter: 'اشترك في نشرتنا البريدية',
    subscribeDescription: 'احصل على آخر التحديثات والعروض الحصرية.',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    subscribe: 'اشتراك',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    aboutDreamBoutique: 'عن Dream Boutique',
    productAddedToCart: 'تمت الإضافة إلى السلة!',
    hasBeenAdded: 'تمت إضافته إلى سلة التسوق.',
    shoppingCart: 'سلة التسوق',
    product: 'المنتج',
    total: 'المجموع',
    subtotal: 'المجموع الفرعي',
    emptyCart: 'سلة التسوق فارغة.',
    continueShopping: 'متابعة التسوق',
    checkout: 'إتمام الشراء',
    applyDiscount: 'تطبيق الخصم',
    discountCode: 'كود الخصم',
    productNamePlaceholder: 'فستان سهرة أنيق',
    selectBrand: 'اختر البراند',
    sortBy: 'فرز حسب',
    priceLowToHigh: 'السعر: من الأرخص للأغلى',
    priceHighToLow: 'السعر: من الأغلى للأرخص',
    searchProducts: 'البحث في المنتجات...',
    noProductsFound: 'لم يتم العثور على منتجات.',
    login: 'تسجيل دخول',
    logout: 'تسجيل خروج',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    loginToDashboard: 'الدخول إلى لوحة التحكم',
    loginFailed: 'فشل تسجيل الدخول. يرجى التحقق من اسم المستخدم وكلمة المرور.',
    loggedIn: 'تم تسجيل الدخول بنجاح!',
    loggedOut: 'تم تسجيل الخروج بنجاح.',
    checkoutTitle: 'إتمام عملية الشراء',
    customerInfo: 'بيانات العميل',
    shippingAddress: 'عنوان الشحن',
    paymentMethod: 'طريقة الدفع',
    orderSummary: 'ملخص الطلب',
    placeOrder: 'تأكيد الطلب',
    orderPlaced: 'تم استلام طلبك بنجاح!',
    orderPlacedDesc: 'شكرًا لثقتكم بنا. سيتم التواصل معكم قريبًا لتأكيد الطلب.',

    // --- المفاتيح الجديدة للخصومات ---
    addDiscount: 'إضافة خصم',
    editDiscount: 'تعديل خصم',
    addNewDiscount: 'إضافة خصم جديد',
    saveChanges: 'حفظ التعديلات',
    discountType: 'نوع الخصم',
    percentage: 'نسبة مئوية',
    fixedAmount: 'مبلغ ثابت',
    discountValue: 'قيمة الخصم',
    enterDiscountValue: 'أدخل قيمة الخصم',
    couponCode: 'رمز الكوبون',
    couponCodeOptional: 'رمز الكوبون (اختياري)',
    enterCouponCodeOptional: 'أدخل رمز الكوبون (اختياري)',
    leaveEmptyForAutomaticDiscount: 'اتركه فارغاً لخصم تلقائي',
    currentDiscounts: 'الخصومات الحالية',
    none: 'لا يوجد',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    actions: 'إجراءات',
    invalidDiscountValue: 'قيمة الخصم غير صحيحة. يجب أن تكون أكبر من صفر.',
    duplicateCouponCode: 'يوجد كوبون بنفس الرمز بالفعل. الرجاء اختيار رمز آخر.',
    discountAdded: 'تم إضافة الخصم بنجاح',
    discountUpdated: 'تم تحديث الخصم بنجاح',
    discountDeleted: 'تم حذف الخصم بنجاح',
    discountStatusChanged: 'تم تغيير حالة الخصم بنجاح',
    noDiscountsAddedYet: 'لم تتم إضافة أي خصومات بعد.',
    jodShort: 'د.أ', // اختصار الدينار الأردني
    error: 'خطأ', // مفتاح جديد لرسائل الأخطاء العامة
    // --- نهاية المفاتيح الجديدة للخصومات ---
  },
  en: {
    totalSales: 'Total Sales',
    totalOrders: 'Total Orders',
    totalProducts: 'Total Products',
    totalCustomers: 'Total Customers',
    home: 'Home',
    cart: 'Cart',
    tracking: 'Track Order',
    notifications: 'Notifications',
    admin: 'Admin Panel',
    search: 'Search by tracking number',
    welcomeTitle: 'Welcome to Dream Boutique',
    welcomeSubtitle: 'Discover the best global brands in one place',
    ourBrands: 'Our Brands',
    featuredProducts: 'Featured Products',
    viewProducts: 'View Products',
    visitInstagram: 'Visit Instagram',
    addToCart: 'Add to Cart',
    classicColorShop: 'Classic Color Shop',
    ghyma68: 'Ghyma68',
    designerrMix: 'Designerr Mix',
    products: 'Products',
    price: 'Price',
    jod: 'JOD',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    dashboard: 'Dashboard',
    productManagement: 'Product Management',
    orderManagement: 'Order Management',
    featuredManagement: 'Featured Products',
    discountManagement: 'Discount Management',
    userManagement: 'Users & Permissions',
    reportsAndSales: 'Reports & Sales',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    productName: 'Product Name',
    productPrice: 'Price',
    productBrand: 'Brand',
    productImage: 'Product Image',
    color: 'Color',
    size: 'Size',
    quantity: 'Quantity',
    uploadImage: 'Upload Product Image',
    save: 'Save',
    cancel: 'Cancel',
    orders: 'Orders',
    addOrder: 'Add Order',
    editOrder: 'Edit Order',
    deleteOrder: 'Delete Order',
    orderNumber: 'Order Number',
    customerName: 'Customer Name',
    phone: 'Phone',
    address: 'Address',
    model: 'Model',
    notes: 'Notes',
    status: 'Status',
    trackingNumber: 'Tracking Number',
    pending: 'Pending',
    shipped: 'Shipped',
    delivered: 'Delivered',
    returned: 'Returned',
    cancelled: 'Cancelled by customer',
    contact: 'Contact Us',
    complaints: 'Complaints & Contact',
    email: 'Email',
    featureNotImplemented: '🚧 This feature isn\'t implemented yet',
    featureNotImplementedDesc: 'But don\'t worry! You can request it in your next prompt! 🚀',
    productAdded: 'Product added successfully',
    productUpdated: 'Product updated successfully',
    productDeleted: 'Product deleted successfully',
    orderAdded: 'Order added successfully',
    orderUpdated: 'Order updated successfully',
    orderDeleted: 'Order deleted successfully',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    aboutUs: 'About Us',
    ourStory: 'Our Story',
    termsAndConditions: 'Terms & Conditions',
    subscribeNewsletter: 'Subscribe to our Newsletter',
    subscribeDescription: 'Get the latest updates and exclusive offers.',
    emailPlaceholder: 'Enter your email',
    subscribe: 'Subscribe',
    allRightsReserved: 'All rights reserved.',
    aboutDreamBoutique: 'About Dream Boutique',
    productAddedToCart: 'Added to cart!',
    hasBeenAdded: 'has been added to your cart.',
    shoppingCart: 'Shopping Cart',
    product: 'Product',
    total: 'Total',
    subtotal: 'Subtotal',
    emptyCart: 'Your shopping cart is empty.',
    continueShopping: 'Continue Shopping',
    checkout: 'Checkout',
    applyDiscount: 'Apply Discount',
    discountCode: 'Discount Code',
    productNamePlaceholder: 'Elegant Evening Dress',
    selectBrand: 'Select Brand',
    sortBy: 'Sort by',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    searchProducts: 'Search products...',
    noProductsFound: 'No products found.',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    loginToDashboard: 'Login to Dashboard',
    loginFailed: 'Login failed. Please check your username and password.',
    loggedIn: 'Logged in successfully!',
    loggedOut: 'Logged out successfully.',
    checkoutTitle: 'Checkout',
    customerInfo: 'Customer Information',
    shippingAddress: 'Shipping Address',
    paymentMethod: 'Payment Method',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    orderPlaced: 'Your order has been placed successfully!',
    orderPlacedDesc: 'Thank you for your purchase. We will contact you shortly to confirm the order.',

    // --- المفاتيح الجديدة للخصومات ---
    addDiscount: 'Add Discount',
    editDiscount: 'Edit Discount',
    addNewDiscount: 'Add New Discount',
    saveChanges: 'Save Changes',
    discountType: 'Discount Type',
    percentage: 'Percentage',
    fixedAmount: 'Fixed Amount',
    discountValue: 'Discount Value',
    enterDiscountValue: 'Enter discount value',
    couponCode: 'Coupon Code',
    couponCodeOptional: 'Coupon Code (Optional)',
    enterCouponCodeOptional: 'Enter coupon code (optional)',
    leaveEmptyForAutomaticDiscount: 'Leave empty for automatic discount',
    currentDiscounts: 'Current Discounts',
    none: 'None',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    actions: 'Actions',
    invalidDiscountValue: 'Invalid discount value. Must be greater than zero.',
    duplicateCouponCode: 'A coupon with this code already exists. Please choose a different code.',
    discountAdded: 'Discount added successfully',
    discountUpdated: 'Discount updated successfully',
    discountDeleted: 'Discount deleted successfully',
    discountStatusChanged: 'Discount status changed successfully',
    noDiscountsAddedYet: 'No discounts added yet.',
    jodShort: 'JOD', // اختصار الدينار الأردني
    error: 'Error', // مفتاح جديد لرسائل الأخطاء العامة
    // --- نهاية المفاتيح الجديدة للخصومات ---
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ar');
  const [direction, setDirection] = useState('rtl');

  useEffect(() => {
    // إصلاح بسيط: إذا لم يجد شيئًا في localStorage، استخدم 'ar' كقيمة افتراضية
    const savedLanguage = localStorage.getItem('dream-boutique-language') || 'ar';
    setLanguage(savedLanguage);
    const newDirection = savedLanguage === 'ar' ? 'rtl' : 'ltr';
    setDirection(newDirection);
    document.documentElement.dir = newDirection;
    document.documentElement.lang = savedLanguage;
  }, []);

  const toggleLanguage = () => {
    const newLanguage = language === 'ar' ? 'en' : 'ar';
    const newDirection = newLanguage === 'ar' ? 'rtl' : 'ltr';

    setLanguage(newLanguage);
    setDirection(newDirection);
    document.documentElement.dir = newDirection;
    document.documentElement.lang = newLanguage;
    localStorage.setItem('dream-boutique-language', newLanguage);
    window.location.reload(); // إعادة تحميل الصفحة لتطبيق الترجمة بالكامل
  };

  const t = (key) => {
    // إذا لم يتم العثور على المفتاح، أعد المفتاح نفسه بدلاً من string فارغ
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      direction,
      toggleLanguage,
      t,
      isRTL: direction === 'rtl'
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
